#!/bin/bash

git add .
git commit -am "commit toughee gitbook `date +%Y-%m-%d" "%H:%M:%S`"
git push  origin master


gitbook build .
#rm -rf /tmp/tougheebook
if [ ! -d /tmp/tougheebook ]; then
    mkdir -p /tmp/tougheebook
    cp -rf _book/* /tmp/tougheebook
    cp CNAME /tmp/tougheebook
    cp -f favicon.ico /tmp/tougheebook/gitbook/images
    cd /tmp/tougheebook
    git init
    git remote add origin git@git.coding.net:toughstruct/toughee-docs.git
    git add .
    git commit -am "deploy gitbook `date +%Y-%m-%d" "%H:%M:%S`"
    git push -f origin master:coding-pages

else
    cp -rf _book/* /tmp/tougheebook
    cp CNAME /tmp/tougheebook
    cp -f favicon.ico /tmp/tougheebook/gitbook/images
    cd /tmp/tougheebook
    git add .
    git commit -am "deploy gitbook `date +%Y-%m-%d" "%H:%M:%S`"
    git push origin master:coding-pages
fi

